# Hypothesis Testing

# Que 1

In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sn
from scipy import stats

In [4]:
#data  the dataset
data=pd.read_csv(r"C:\Users\sai\Downloads\Cutlets.csv")

In [5]:
data.head()

Unit A  Unit B
0  6.8090  6.7703
1  6.4376  7.5093
2  6.9157  6.7300
3  7.3012  6.7878
4  7.4488  7.1522

In [6]:
unit_A = data.iloc[:,0]
unit_B = data.iloc[:,1]

In [8]:
stat_value,p_value = stats.ttest_ind(unit_A,unit_B)
print(stat_value,p_value)

0.7228688704678063 0.4722394724599501


# Que 2


In [9]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sn
from scipy import stats

In [11]:
data =pd.read_csv(r"C:\Users\sai\Downloads\LabTAT.csv")

In [12]:
data.head()

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
0        185.35        165.53        176.70        166.13
1        170.49        185.91        198.45        160.79
2        192.77        194.92        201.23        185.18
3        177.33        183.00        199.61        176.42
4        193.41        169.57        204.63        152.60

In [14]:
lab1 = data.iloc[:,0]
lab2 = data.iloc[:,1]
lab3 = data.iloc[:,2]
lab4 = data.iloc[:,3]

In [15]:
stat_value,p_value = stats.f_oneway(lab1,lab2,lab3,lab4)
print(stat_value,p_value)

118.70421654401437 2.1156708949992414e-57


# Que 3

In [2]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sn
from scipy import stats

In [3]:
data = pd.read_csv(r"C:\Users\sai\Downloads\BuyerRatio.csv")

In [4]:
data.head()

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [5]:
Males=data.iloc[0,1:]
Females=data.iloc[1,1:]

In [6]:
data1=[Males,Females]
print(data1)

[East      50
West     142
North    131
South     70
Name: 0, dtype: object, East      435
West     1523
North    1356
South     750
Name: 1, dtype: object]


In [7]:
result = stats.chi2_contingency(data1)
print(result)

(1.595945538661058, 0.6603094907091882, 3, array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
       [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]]))


In [8]:
stat_value=result[0]
pi_value=result[1]
df=result[2]
stat_value,pi_value,df

(1.595945538661058, 0.6603094907091882, 3)

In [9]:
expected_value=result[3]
expected_value

array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
       [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]])

# Que 4

In [10]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sn
from scipy import stats

In [13]:
data=pd.read_csv(r"C:\Users\sai\Downloads\Costomer+OrderForm.csv")

In [14]:
data.head()

Phillippines   Indonesia       Malta       India
0   Error Free  Error Free   Defective  Error Free
1   Error Free  Error Free  Error Free   Defective
2   Error Free   Defective   Defective  Error Free
3   Error Free  Error Free  Error Free  Error Free
4   Error Free  Error Free   Defective  Error Free

In [16]:
phillippines=data.Phillippines.value_counts()
indonesia=data.Indonesia.value_counts()
malta=data.Malta.value_counts()
india=data.India.value_counts()

In [18]:
phillippines.values
indonesia.values
malta.values
india.values

array([280,  20], dtype=int64)

In [19]:
df_1=[phillippines[0],indonesia[0],malta[0],india[0]]
df_2=[phillippines[1],indonesia[1],malta[1],india[1]]
df=[df_1,df_2]
df

[[271, 267, 269, 280], [29, 33, 31, 20]]

In [20]:
result=stats.chi2_contingency(df)
result

(3.858960685820355,
 0.2771020991233135,
 3,
 array([[271.75, 271.75, 271.75, 271.75],
        [ 28.25,  28.25,  28.25,  28.25]]))

In [21]:
stat_value=result[0]
pi_value=result[1]
df=result[2]
stat_value,pi_value,df

(3.858960685820355, 0.2771020991233135, 3)